### PR TITLE
december 16 version

### PR DESCRIPTION
**Pull request by Yago**
@gido need review for December version of our browser support document

### CODE REVIEW

**Comment by Yago** [comment]
@gido review please

**Comment by Yago** [comment]
@gido 😭😭😭😭😭😭😭😭😭
@antistatique/antistatique We really have to be reactive on this side

**Comment by Yago** [comment]
capture_d ecran_2017-02-01_a_13_52_25

**Comment by gido** [comment]
OK, I approve the deprecation of IE10 (less than 0.3% in Switzerland market).
The client need to be notified of deprecation.

**Comment by Saniha** [comment]
Which client @gido ?

**Pull request merged**
